// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtIoiPaA98ubDHOKIwAtxutKuvmeORtAI',
    appId: '1:511355181571:web:b390eba99a6e7470d24c36',
    messagingSenderId: '511355181571',
    projectId: 'usv-hub',
    authDomain: 'usv-hub.firebaseapp.com',
    storageBucket: 'usv-hub.appspot.com',
    measurementId: 'G-28D5FKPKYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpiCKPEFz7WHmFPTXhCX2dFspMqtbNu3E',
    appId: '1:511355181571:android:542d4c499be1b791d24c36',
    messagingSenderId: '511355181571',
    projectId: 'usv-hub',
    storageBucket: 'usv-hub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLFCbQa-z-tpR_3WHxuQMSjHsWPpC8Ua8',
    appId: '1:511355181571:ios:1f2fa955d841e7c2d24c36',
    messagingSenderId: '511355181571',
    projectId: 'usv-hub',
    storageBucket: 'usv-hub.appspot.com',
    iosBundleId: 'com.example.desktopMath',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLFCbQa-z-tpR_3WHxuQMSjHsWPpC8Ua8',
    appId: '1:511355181571:ios:1f2fa955d841e7c2d24c36',
    messagingSenderId: '511355181571',
    projectId: 'usv-hub',
    storageBucket: 'usv-hub.appspot.com',
    iosBundleId: 'com.example.desktopMath',
  );
}
